### ISSUE TITLE
Первые баги

### ISSUE THREAD

**Issue by str1dey** [SickerDevelopment/rp-wow-css-patcher#1]
1. не показывает ошибки
2. отказывается вставлять фотки пока ты не заполнишь все поля
3. В главном меню кнопка "ПРОФИЛЬ", а когда непосредственно работаешь с сайтом там написано "оформление анкеты"
![изображение](https://github.com/user-attachments/assets/0252701e-9c72-4cb5-822b-3b922b654ac2)
![изображение](https://github.com/user-attachments/assets/f5276efe-8a46-44ee-a4c7-78d9f907f13d)

**Comment by SickerDevelopment** [comment]
Исправлены ошибки правописания на страницах.
