### ISSUE TITLE
Ошибка при замене лого

### ISSUE THREAD

**Issue by Akella497** [SickerDevelopment/rp-wow-css-patcher#2]
[Приложите скриншоты, или видеоматериалы](https://imgur.com/a/N2vZIOq)
Ссылка на изображение: https://i.imgur.com/BERtRVV.png
Не работает функционал замены логотипа (?). Также пробовал прожать галку "использовать перезагрузку..". Не помогло.

**Comment by SickerDevelopment** [comment]
#1 Уже решена проблема, версия 0.0.3 не такая глючная
